### ISSUE TITLE
زمان اضافه شدن رجا و سفیر

### ISSUE THREAD

**Issue by abo72** [keyone2693/IRTrainDotNet#1]
سلام کی رجا رو اضافه میکیند باتوجه به اینکه بیشتر قطارا برای رجاس؟

**Comment by keyone2693** [comment]
با سلام
متاسفانه در دادن داکیومنت ها بسیار سختیگیری میکنن
به محض دریافت رجا فعال میشه
کد هاش نوشته شده نیاز به یک سری جزییات داره از سمت رجا
